### ISSUE TITLE
"Play_Kikimora_sweep" sound needs fade-in/fade-out

### ISSUE THREAD

**Issue by Xulu-u** [Broken-Gem-Studio/The-Witcher-Ties-of-Destiny#10]
## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Visual 
* [ ] Physics 
* [ x] Audio 
* [ ] Particles
* [ ] Resource Management & Save/Load 
* [ ] Materials 
* [ ] Components
* [ ] Game Objects
* [ ] UI/UX 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [ x] Cosmetic 

## Reproduction

 1. When Kikimora uses its sweep attacks
 
 2. 
 
 3. 

 4. 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

## Build
- **Please specify the build:** ``Insert the build here``
0.6.3

**Comment by DidacRomero** [comment]
This issue has been fixed, test the sound, if it is good enough message me and I will close this issue.
@OhCaXulu @AdrianFR99

**Comment by DidacRomero** [comment]
I insist @OhCaXulu @AdrianFR99
