### ISSUE TITLE
Audio of HUD potions/evade not working properly

### ISSUE THREAD

**Issue by Megaoski** [Broken-Gem-Studio/The-Witcher-Ties-of-Destiny#4]
## Bug Description
The audio fx of using a potion when you have 0 and doing the evade while having no energy sound 1 step before they should. Instead of playing when you have 1 potion left and use it(so now is 0) should only sound when you have 0 and not in the in between step

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Playable Characters
* [ ] Enemies 
* [x] User Interface 
* [ ] Camera 
* [ ] Menu 
* [ ] Cinematic (Village Level)
* [ ] Cinematic (Forest Level)
* [ ] Village Level (tutorial)
* [ ] Forest Level
* [ ] Scene Transition 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Use potions of a kind until you have 1 left
 
 2. Consume it, the sound will pop up beacause the value has become 0 in the process
 
 3. The same procedure with the evade, press A when the energy is above 33% but below 66%(second part of the bar)

 4. If the enery becomes less than 33% after using the evade, the sound will pop up anyways

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Sound should only pop up if player is using potions and has 0.
Sound should only pop up if player is using evade and has less than 33% of energy

### Actual result:
Sound pops up if player has 1 potion left and consumes it
Sound pops up if player has more than 33% of eng and uses evade

## Build
- **Please specify the build:** ``Alpha 2``

## Observations and Additional Information
This is a mistake on the Energy Bar and Potions HUD scripts

**Comment by Scarzard** [comment]
Seems to work in Official Build 1.3
