### ISSUE TITLE
Gained Potions after breaking box/barrels not being gained by the player

### ISSUE THREAD

**Issue by Megaoski** [Broken-Gem-Studio/The-Witcher-Ties-of-Destiny#5]
## Bug Description
When player destroys a prop that grants a potion of whatever type, the player doesnt gain the potion that the barrel grants by the particles

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Playable Characters
* [ ] Enemies 
* [ ] User Interface 
* [ ] Camera 
* [ ] Menu 
* [ ] Cinematic (Village Level)
* [ ] Cinematic (Forest Level)
* [ ] Village Level (tutorial)
* [ ] Forest Level
* [ ] Scene Transition 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Have whatever number of potions left
 
 2. Destroy a propthat grants potions
 
 3. Check that the number in the HUD is not uploading properly

 4. Check that if Geralt/Jaskier had 0 potions before, they cant do the action to drink a new one after gaining one detroying the prop

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
The player should gain potions until a limit when detroying the prop

### Actual result:
Its just visual, in the inventory remain the same

## Build
- **Please specify the build:** ``Alpha 2``

## Observations and Additional Information
Probably comes from the destructible prop script, since Geralt cant do the action of consuming a new potion gained if he had 0, so its not coming from the HUD

**Comment by Scarzard** [comment]
Works on the latest build, potions now fall to the ground
