### ISSUE TITLE
Colliders of enemies should be detroyed when they die

### ISSUE THREAD

**Issue by Megaoski** [Broken-Gem-Studio/The-Witcher-Ties-of-Destiny#6]
## Bug Description
When killing an enemy the collider remain during a while even if they have been killed, it slows the player and can be a problem when facing multiple enemies(spawner)

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Playable Characters
* [x] Enemies 
* [ ] User Interface 
* [ ] Camera 
* [ ] Menu 
* [ ] Cinematic (Village Level)
* [ ] Cinematic (Forest Level)
* [ ] Village Level (tutorial)
* [ ] Forest Level
* [ ] Scene Transition 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [x] Game stopper/slower
- [ ] Cosmetic 

## Reproduction

 1. Kill and enemy
 
 2. Walk throught the dead body
 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Collider should be erased when enemy is dead

### Actual result:
It stays with the body

## Build
- **Please specify the build:** ``Alpha 2``

**Comment by Scarzard** [comment]
Fixed by @knela96
