### ISSUE TITLE
Nearby enemies boolean not working properly

### ISSUE THREAD

**Issue by Megaoski** [Broken-Gem-Studio/The-Witcher-Ties-of-Destiny#7]
## Bug Description
When an enemy is near, the boolean sometimes works correctly so the combat music starts to play and the sword of the HUD unsheathes, but is doesnt work properly always

## Type of Bug 
Select the type of bug with and "x" ([x])

* [x] Playable Characters
* [x] Enemies 
* [ ] User Interface 
* [ ] Camera 
* [ ] Menu 
* [ ] Cinematic (Village Level)
* [ ] Cinematic (Forest Level)
* [ ] Village Level (tutorial)
* [ ] Forest Level
* [ ] Scene Transition 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Get closer to an encounter and watch the sword HUD unsheath and combat music play
 
 2.  Sometimes this may not work even when you are close to enemies
 

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [ ] Always
* [ ] Very Often
* [x] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Combat music & HUD sword unsheathing should happen always a player is in combat

### Actual result:
Sometimes its not happening

## Build
- **Please specify the build:** ``Alpha 2``

## Observations and Additional Information
I assume this comes from the nearby enemies boolean not working properly

**Comment by DidacRomero** [comment]
Right now in the Interactive Musci implementation this issue has been solved, You can use the mMusic Manager boolean Enemies_Nearby in order to properly identify it wheter Geralt or jaskier are near an enemy, it goes without saying that this also fixes the issue with the music
