### ISSUE TITLE
Spawner enemey scream collidews with his sons

### ISSUE THREAD

**Issue by Megaoski** [Broken-Gem-Studio/The-Witcher-Ties-of-Destiny#8]
## Bug Description
When the enemy spawner uses his scream and has his "children" in front of huim, the scream collides with their bodies and does not go to the direction of the player

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Playable Characters
* [x] Enemies 
* [ ] User Interface 
* [ ] Camera 
* [ ] Menu 
* [ ] Cinematic (Village Level)
* [ ] Cinematic (Forest Level)
* [ ] Village Level (tutorial)
* [ ] Forest Level
* [ ] Scene Transition 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Fight an spawner enemy
 
 2. Wait that he spawns children and move them so he's behind
 
 3. When he uses the scream the children will redirect the scream because of the collision

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Scream should not collide with the enemies 

### Actual result:
It does

## Build
- **Please specify the build:** ``Alpha 2`

## Observations and Additional Information
Furthermore, i can avoid the scream easily even slow walking, maybe make it faster so the player has to use the evade move to not be hit

**Comment by Scarzard** [comment]
Doesn't redirect the actual collider, the particles hit the minions and, visually, it appears that it messes with the puke's trajectory, but it doesn't, the colliders stays in place.

2 solutions: create a separate layer for the puke (kinda overkill), make enemies unable to collide with particles.

**Comment by Scarzard** [comment]
Tested in Official Build 1.3 and appears that it doesn't happen anymore. Probably because the Screamer Ghoul model is larger and the emitter is placed in his head. Being taller makes the puke particles travel above the minions. 

Closing this because it is fixed.
