### ISSUE TITLE
Forest cinematic sound working after i used skip

### ISSUE THREAD

**Issue by Megaoski** [Broken-Gem-Studio/The-Witcher-Ties-of-Destiny#9]
## Bug Description
After using the skip button to avoid the forest cinematic, the sound keeps goin on until the levels has loaded

## Type of Bug 
Select the type of bug with and "x" ([x])

* [ ] Playable Characters
* [ ] Enemies 
* [ ] User Interface 
* [ ] Camera 
* [ ] Menu 
* [ ] Cinematic (Village Level)
* [x] Cinematic (Forest Level)
* [ ] Village Level (tutorial)
* [ ] Forest Level
* [ ] Scene Transition 
* [ ] Other

## Severity
Select the severity of bug affection and mark with "x" ([x])

- [ ] Crash 
- [ ] Game stopper/slower
- [x] Cosmetic 

## Reproduction

 1. Start  level 2
 
 2.  Press skip button during the cinematic

## Frequency
Select the frequency with which the bug appears and mark it "x" ([x])

* [x] Always
* [ ] Very Often
* [ ] Usually
* [ ] Few Times
* [ ] Few Times under specific conditions

### Expected result:
Audio should stop

### Actual result:
It doesnt

## Build
- **Please specify the build:** ``Alpha 2``

**Comment by DidacRomero** [comment]
this issue has been solved and will now be closed!
